//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod ingredient;
pub mod recipe;
pub mod recipe_ingredient;
pub mod unit;
pub mod user;
pub use async_graphql;
pub use sea_orm;
