[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies.async-graphql]
version = "7.0.5"

[dependencies.sea-orm]
version = "^0.12.0"
features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]
